language: java
jdk: openjdk7
deploy:
  provider: heroku
  api_key:
    secure: SqIiXAMJqyZRd68jmAuCWZ/MJliOJN3FfY1wejwLdIraYncC6FNJCKcqhMykNecftQxMvYruGMl036URMIQ3Cb1FDpKRt+8ne0QIR5JCEwNZd9s+255L/k3MOScOr4EPCWMM8lHw6AXzZ7G6+8cgyPRxEiODEOHg7DaPsvZMjts=
  app: mrkumalo
  on:
    repo: MrKumalo/Kumalo
env:
  global:
    secure: GWKT3z4/PWMP5UwYGfSn54YZx32D9HpTlDrXjxat+e98POkBTaF7I0THPm69zMFphCQp/0Ca6DIGYR5TOQM4ppUs7xWEBZB+q/UhfrWhi5V+cGd0h246yOAsz9QIgjwoLRlNKr/1kvW77LtCWYfaTyR+UG1O+AtdkZbPKReSRUw=
