language: java
jdk: openjdk7
deploy:
  provider: heroku
  api_key:
    secure: SqIiXAMJqyZRd68jmAuCWZ/MJliOJN3FfY1wejwLdIraYncC6FNJCKcqhMykNecftQxMvYruGMl036URMIQ3Cb1FDpKRt+8ne0QIR5JCEwNZd9s+255L/k3MOScOr4EPCWMM8lHw6AXzZ7G6+8cgyPRxEiODEOHg7DaPsvZMjts=
  app: mrkumalo
  on:
    repo: MrKumalo/Kumalo
env:
  global:
    secure: GWKT3z4/PWMP5UwYGfSn54YZx32D9HpTlDrXjxat+e98POkBTaF7I0THPm69zMFphCQp/0Ca6DIGYR5TOQM4ppUs7xWEBZB+q/UhfrWhi5V+cGd0h246yOAsz9QIgjwoLRlNKr/1kvW77LtCWYfaTyR+UG1O+AtdkZbPKReSRUw=

after_success:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:mrkumalo.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- yes | git push heroku master
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- heroku plugins:install https://github.com/ddollar/heroku-anvil
- heroku build -r mrkumalo  -b https://github.com/heroku/heroku-buildpack-ruby.git

install:
- gem install selenium-webdriver

script:
before_deploy:
- sh bin/before_deploy
after_script:
- sh -e /etc/init.d/xvfb stop
