language: java
jdk: openjdk7
deploy:
  provider: heroku
  api_key: d1a12cf8-b3df-49bf-be45-d5be3c33ff8b
    secure: SqIiXAMJqyZRd68jmAuCWZ/MJliOJN3FfY1wejwLdIraYncC6FNJCKcqhMykNecftQxMvYruGMl036URMIQ3Cb1FDpKRt+8ne0QIR5JCEwNZd9s+255L/k3MOScOr4EPCWMM8lHw6AXzZ7G6+8cgyPRxEiODEOHg7DaPsvZMjts=
  app: mrkumalo
  on:
    repo: MrKumalo/Kumalo
env:
  global:
    secure: A3c+xp2wRWejKiT+afCDsC2q/rVxT3LZ5gscR0itFQRAnqJvc0ccK1Cr4lRNdesXkRWbm8+/89TkivY7LAAbpTt/cAwgr72B8LUh9PxyfSjJ+/YZmMS6hDzvvK4LCbBHv+ibgazuuyQ0cbvBGG9At8i7HFiVInjTetKuZgKI4Ts=
