language: java
jdk: openjdk7
deploy:
  provider: heroku
  api_key:
    secure: W/5TwUFq8vETHLOtn01NviiGluhLT8no9HXAzHz2vDbV5jdqCHd0HaZ2miJreuPxGnJnXx3i0NEzfx9sRsB8g9MxP9FxR7H3iulsZkf9g6mPWwnlzlTPl449NhtDvx60RjEOKHg2JykNjBeCYSJgxE/tlO0ZUftewH6l9cWOYFI=
  app: mrkumalo
  on:
    repo: MrKumalo/Kumalo
env:
  global:
  - secure: W/5TwUFq8vETHLOtn01NviiGluhLT8no9HXAzHz2vDbV5jdqCHd0HaZ2miJreuPxGnJnXx3i0NEzfx9sRsB8g9MxP9FxR7H3iulsZkf9g6mPWwnlzlTPl449NhtDvx60RjEOKHg2JykNjBeCYSJgxE/tlO0ZUftewH6l9cWOYFI=
  - secure: VBuxBtjGQkh1kaQw2upcZYu5XbR9nfS338pkIF++XOZAkLBBLy3qxhfnNDIiYpF8PzArN5fLie7oXwdHhu4viDDmEKI5SeN3VgeQgTFKWwX8NVUEKrpDWdACh5TCHMIFmS9Sy+MzxIlCfIut26Lx+4dhfNSckCn3iqDDb2PcWms=
after_success:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- git remote add heroku git@heroku.com:kumalostaging.git
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- yes | git push heroku master
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- heroku plugins:install https://github.com/ddollar/heroku-anvil
- heroku build -r kumalostaging  -b https://github.com/heroku/heroku-buildpack-ruby.git
install:
- gem install selenium-webdriver
script: 
before_deploy:
- sh bin/before_deploy
after_script:
- sh -e /etc/init.d/xvfb stop
